excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://nchanin.github.io
title: Lecture Notes
email: nchanin@yahoo.com
author: Noah Chanin
description: Review of online lectures about a myriad of topics: Information Security, Machine Learning, Systems Design, Math, and Programming
paginate: 3
google_analytics: 